from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import Engine, inspect

from tests.conftest import alembic_config

MVP_TABLES = {"employees", "compensation", "fx_rates"}


def table_names(engine: Engine) -> set[str]:
    return set(inspect(engine).get_table_names())


def test_migration_downgrades_and_upgrades_cleanly(
    migrated_engine: Engine, test_database_url: str
) -> None:
    config = alembic_config(test_database_url)
    assert MVP_TABLES <= table_names(migrated_engine)

    command.downgrade(config, "base")
    assert not (MVP_TABLES & table_names(migrated_engine))

    command.upgrade(config, "head")
    assert MVP_TABLES <= table_names(migrated_engine)


def test_migrations_match_models(test_database_url: str, migrated_engine: Engine) -> None:
    try:
        command.check(alembic_config(test_database_url))
    except AutogenerateDiffsDetected as drift:
        raise AssertionError(f"models and migrations have drifted: {drift}") from drift
